# -*- coding: utf-8 -*-
"""week4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g5skqHGuzmhmf9N5wE43WM2rqMbeG0X8
"""

# ============================================================
# Week 4 - Cell 1
# 환경 설정 + 데이터/폴더 확인
# ============================================================

from google.colab import drive
drive.mount('/content/drive')

import os
import random
import numpy as np
import torch

# ------------------------------------------------------------
# 1. 경로 설정
# ------------------------------------------------------------
BASE_DIR = "/content/drive/MyDrive/individual_research"
DATA_DIR = os.path.join(BASE_DIR, "data")
HR_DIR = os.path.join(DATA_DIR, "HR")
SRC_DIR = os.path.join(BASE_DIR, "src")

RESULT_DIR = os.path.join(BASE_DIR, "results", "week4")

CHECKPOINT_DIR = os.path.join(RESULT_DIR, "checkpoints")
FIGURE_DIR = os.path.join(RESULT_DIR, "figures")

os.makedirs(RESULT_DIR, exist_ok=True)
os.makedirs(CHECKPOINT_DIR, exist_ok=True)
os.makedirs(FIGURE_DIR, exist_ok=True)

# ------------------------------------------------------------
# 2. Random seed 고정
# ------------------------------------------------------------
SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ------------------------------------------------------------
# 3. Device
# ------------------------------------------------------------
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

# ------------------------------------------------------------
# 4. HR 이미지 확인
# ------------------------------------------------------------
valid_ext = (".png", ".jpg", ".jpeg", ".bmp")

hr_files = sorted([
    f for f in os.listdir(HR_DIR)
    if f.lower().endswith(valid_ext)
])

print("=" * 60)
print("Week 4 Setup")
print("=" * 60)

print("Device     :", device)
print("Seed       :", SEED)
print("HR dir     :", HR_DIR)
print("Result dir :", RESULT_DIR)
print("HR images  :", len(hr_files))

if len(hr_files) > 0:
    print("First image:", hr_files[0])

print("=" * 60)

# ============================================================
# Week 4 - Cell 2
# Exposure-dependent degradation + Noise ON/OFF
# ============================================================

import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt

from PIL import Image
from torchvision.transforms.functional import to_tensor


# ------------------------------------------------------------
# 1. Week 3에서 사용한 exposure 설정
# ------------------------------------------------------------

EXPOSURES = [3, 7, 11, 15, 19]

MOTION_ANGLE = 45.0

# Gaussian noise
NOISE_SIGMA = 5 / 255.0


# ------------------------------------------------------------
# 2. Motion blur kernel 생성
# ------------------------------------------------------------

def make_motion_kernel(length, angle=45.0):

    # kernel size는 홀수로 맞춤
    length = int(round(length))

    if length % 2 == 0:
        length += 1

    length = max(length, 1)

    kernel = np.zeros((length, length), dtype=np.float32)

    center = length // 2

    # 가운데에 수평선 생성
    kernel[center, :] = 1.0

    # 원하는 angle로 회전
    rotation_matrix = cv2.getRotationMatrix2D(
        (center, center),
        angle,
        1.0
    )

    kernel = cv2.warpAffine(
        kernel,
        rotation_matrix,
        (length, length)
    )

    kernel /= (kernel.sum() + 1e-8)

    return kernel


# ------------------------------------------------------------
# 3. Exposure -> Blur length
# ------------------------------------------------------------

def exposure_to_blur_length(exposure):
    """
    Week 3에서 확인한 설정:
    exposure가 커질수록 motion blur가 강해짐.

    exposure = 3  -> length 3
    exposure = 7  -> length 7
    exposure = 11 -> length 11
    exposure = 15 -> length 15
    exposure = 19 -> length 19
    """
    return int(exposure)


# ------------------------------------------------------------
# 4. Week 4 degradation 함수
# ------------------------------------------------------------

def degrade_image(
    hr_tensor,
    exposure,
    noise_on=True,
    noise_sigma=NOISE_SIGMA,
    scale=2
):
    """
    Input
    -----
    hr_tensor : [C,H,W], range [0,1]
    exposure  : exposure condition

    Pipeline
    --------
    HR
      -> exposure-dependent motion blur
      -> downsample
      -> bicubic upsample
      -> optional Gaussian noise
    """

    # [C,H,W] -> [H,W,C]
    img = hr_tensor.permute(1, 2, 0).cpu().numpy()

    # -----------------------------------------
    # Exposure-dependent motion blur
    # -----------------------------------------

    blur_length = exposure_to_blur_length(exposure)

    kernel = make_motion_kernel(
        blur_length,
        MOTION_ANGLE
    )

    blurred = cv2.filter2D(
        img,
        -1,
        kernel,
        borderType=cv2.BORDER_REFLECT
    )

    h, w = blurred.shape[:2]

    # -----------------------------------------
    # Downsample
    # -----------------------------------------

    lr = cv2.resize(
        blurred,
        (w // scale, h // scale),
        interpolation=cv2.INTER_AREA
    )

    # -----------------------------------------
    # Bicubic upsample
    # -----------------------------------------

    degraded = cv2.resize(
        lr,
        (w, h),
        interpolation=cv2.INTER_CUBIC
    )

    # -----------------------------------------
    # Optional Gaussian noise
    # -----------------------------------------

    if noise_on:

        noise = np.random.normal(
            0.0,
            noise_sigma,
            degraded.shape
        ).astype(np.float32)

        degraded = degraded + noise

    degraded = np.clip(
        degraded,
        0.0,
        1.0
    ).astype(np.float32)

    degraded_tensor = torch.from_numpy(
        degraded
    ).permute(2, 0, 1)

    return degraded_tensor


print("Exposure settings :", EXPOSURES)
print("Motion angle      :", MOTION_ANGLE)
print("Noise sigma       :", NOISE_SIGMA)

for e in EXPOSURES:
    print(
        f"Exposure {e:2d} -> "
        f"Blur length {exposure_to_blur_length(e):2d}"
    )

# ============================================================
# Week 4 - Cell 3
# Exposure별 degradation 시각화
# Noise OFF vs Noise ON
# ============================================================

import os
import matplotlib.pyplot as plt
from PIL import Image
from torchvision.transforms.functional import to_tensor


# ------------------------------------------------------------
# 1. HR 이미지 하나 선택
# ------------------------------------------------------------

sample_path = os.path.join(HR_DIR, hr_files[0])

hr_img = Image.open(sample_path).convert("RGB")
hr_tensor = to_tensor(hr_img)

print("Sample image :", sample_path)
print("HR shape     :", hr_tensor.shape)


# ------------------------------------------------------------
# 2. Noise ON/OFF 결과 생성
# ------------------------------------------------------------

results_off = []
results_on = []

for exposure in EXPOSURES:

    # 같은 exposure, Noise OFF
    degraded_off = degrade_image(
        hr_tensor,
        exposure=exposure,
        noise_on=False
    )

    # 같은 exposure, Noise ON
    degraded_on = degrade_image(
        hr_tensor,
        exposure=exposure,
        noise_on=True
    )

    results_off.append(degraded_off)
    results_on.append(degraded_on)


# ------------------------------------------------------------
# 3. 시각화
# ------------------------------------------------------------

fig, axes = plt.subplots(
    2,
    len(EXPOSURES),
    figsize=(18, 7)
)

for i, exposure in enumerate(EXPOSURES):

    # Noise OFF
    axes[0, i].imshow(
        results_off[i].permute(1, 2, 0).numpy()
    )

    axes[0, i].set_title(
        f"Exposure {exposure}\nNoise OFF"
    )

    axes[0, i].axis("off")


    # Noise ON
    axes[1, i].imshow(
        results_on[i].permute(1, 2, 0).numpy()
    )

    axes[1, i].set_title(
        f"Exposure {exposure}\nNoise ON"
    )

    axes[1, i].axis("off")


plt.suptitle(
    "Exposure-dependent Degradation: Noise OFF vs ON",
    fontsize=16
)

plt.tight_layout()

save_path = os.path.join(
    FIGURE_DIR,
    "exposure_noise_on_off_check.png"
)

plt.savefig(
    save_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()

print("Saved:", save_path)

# ============================================================
# Week 4 - Cell 4
# Exposure split + Train / Val / Test image split
# ============================================================

import random


# ------------------------------------------------------------
# 1. Exposure split
# ------------------------------------------------------------

# 학습 중 직접 보는 exposure
TRAIN_EXPOSURES = [3, 7, 11, 15, 19]

# 학습 범위 안이지만 직접 보지 않은 exposure
INTERP_EXPOSURES = [5, 9, 13, 17]

# 학습 범위 밖의 exposure
EXTRAP_EXPOSURES = [21, 25]


# ------------------------------------------------------------
# 2. Exposure normalization
# ------------------------------------------------------------
# Conditioning 모델에 실제로 들어가는 exposure 값
#
# Train 범위:
#   exposure 3  -> 0.0
#   exposure 19 -> 1.0
#
# Extrapolation은 1.0을 넘어가는 것을 그대로 허용

EXP_MIN = min(TRAIN_EXPOSURES)
EXP_MAX = max(TRAIN_EXPOSURES)


def normalize_exposure(exposure):
    return (
        float(exposure) - EXP_MIN
    ) / (
        EXP_MAX - EXP_MIN
    )


# ------------------------------------------------------------
# 3. HR image split
# ------------------------------------------------------------
# 피드백 반영:
#
# Train / Validation / Test를 서로 완전히 분리
#
# 전체 35장
# Train = 25
# Val   = 5
# Test  = 5
#
# SEED를 고정한 shuffle이므로 항상 같은 split이 생성됨.

all_hr_files = sorted(hr_files)

assert len(all_hr_files) >= 35, \
    f"Expected at least 35 HR images, but found {len(all_hr_files)}"


# 원본 리스트를 건드리지 않도록 copy
shuffled_files = all_hr_files.copy()

split_rng = random.Random(SEED)
split_rng.shuffle(shuffled_files)


train_files = shuffled_files[:25]
val_files   = shuffled_files[25:30]
test_files  = shuffled_files[30:35]


# ------------------------------------------------------------
# 4. Split overlap 검사
# ------------------------------------------------------------

assert set(train_files).isdisjoint(val_files)
assert set(train_files).isdisjoint(test_files)
assert set(val_files).isdisjoint(test_files)


# ------------------------------------------------------------
# 5. 설정 출력
# ------------------------------------------------------------

print("=" * 70)
print("Week 4 Experimental Split")
print("=" * 70)


print("\n[Image split]")
print("Total :", len(all_hr_files))
print("Train :", len(train_files))
print("Val   :", len(val_files))
print("Test  :", len(test_files))


print("\n[Exposure split]")

print("\nSeen / Training exposure")
for e in TRAIN_EXPOSURES:
    print(
        f"  exposure={e:2d} | "
        f"normalized={normalize_exposure(e):.3f}"
    )


print("\nInterpolation exposure")
for e in INTERP_EXPOSURES:
    print(
        f"  exposure={e:2d} | "
        f"normalized={normalize_exposure(e):.3f}"
    )


print("\nExtrapolation exposure")
for e in EXTRAP_EXPOSURES:
    print(
        f"  exposure={e:2d} | "
        f"normalized={normalize_exposure(e):.3f}"
    )


print("\n[Train examples]")
print(train_files[:5])

print("\n[Validation files]")
print(val_files)

print("\n[Test files]")
print(test_files)


print("\nSplit overlap check : PASS")

print("=" * 70)

# ============================================================
# Week 4 - Cell 5
# Dataset + DataLoader
# ============================================================

import os
import random
import numpy as np
import torch

from PIL import Image
from torch.utils.data import Dataset, DataLoader
from torchvision.transforms.functional import to_tensor


# ------------------------------------------------------------
# 1. 기본 설정
# ------------------------------------------------------------

PATCH_SIZE = 48
BATCH_SIZE = 8
#이게 중요한 이유는 Week 4의 핵심이 "patch size를 바꿨더니 성능이 달라졌다"가 아니라,
#동일한 SRCNN 학습 조건에서 exposure 정보를 주면 복원이 좋아지는가?
#를 비교하는 것이기 때문이다!그래서 기존 조건을 고정함!(patch size)


# ------------------------------------------------------------
# 2. Week 4 Dataset
# ------------------------------------------------------------

class Week4ExposureDataset(Dataset):

    def __init__(
        self,
        hr_dir,
        file_list,
        exposures,
        patch_size=48,
        training=False,
        noise_on=True
    ):

        self.hr_dir = hr_dir
        self.file_list = list(file_list)
        self.exposures = list(exposures)

        self.patch_size = patch_size
        self.training = training
        self.noise_on = noise_on

        # ----------------------------------------------------
        # 각 image × exposure 조합을 하나의 sample로 구성
        #
        # 예:
        # image_01 × exposure 3
        # image_01 × exposure 7
        # ...
        # image_02 × exposure 3
        # ...
        # ----------------------------------------------------

        self.samples = []

        for filename in self.file_list:
            for exposure in self.exposures:

                self.samples.append(
                    (filename, exposure)
                )


    def __len__(self):

        return len(self.samples)


    def _crop(self, img_tensor):

        _, h, w = img_tensor.shape

        ps = self.patch_size

        if h < ps or w < ps:
            raise ValueError(
                f"Image size ({h},{w}) is smaller "
                f"than PATCH_SIZE={ps}"
            )

        # --------------------------------------------
        # Train:
        # random crop
        # --------------------------------------------

        if self.training:

            top = random.randint(
                0,
                h - ps
            )

            left = random.randint(
                0,
                w - ps
            )

        # --------------------------------------------
        # Validation / Test:
        # center crop
        #
        # 매 평가마다 정확히 같은 영역을 사용
        # --------------------------------------------

        else:

            top = (h - ps) // 2
            left = (w - ps) // 2


        crop = img_tensor[
            :,
            top:top + ps,
            left:left + ps
        ]

        return crop


    def __getitem__(self, idx):

        filename, exposure = self.samples[idx]

        # --------------------------------------------
        # HR image load
        # --------------------------------------------

        path = os.path.join(
            self.hr_dir,
            filename
        )

        img = Image.open(path).convert("RGB")

        hr = to_tensor(img)

        # --------------------------------------------
        # Crop
        # --------------------------------------------

        hr = self._crop(hr)


        # --------------------------------------------
        # Degradation
        #
        # HR
        # -> exposure-dependent blur
        # -> downsample
        # -> bicubic upsample
        # -> optional noise
        # --------------------------------------------

        degraded = degrade_image(
            hr,
            exposure=exposure,
            noise_on=self.noise_on
        )


        # --------------------------------------------
        # Exposure conditioning value
        # --------------------------------------------

        exposure_norm = torch.tensor(
            normalize_exposure(exposure),
            dtype=torch.float32
        )


        return {
            "input": degraded,
            "target": hr,
            "exposure": exposure_norm,
            "exposure_raw": torch.tensor(
                exposure,
                dtype=torch.float32
            ),
            "filename": filename
        }


# ------------------------------------------------------------
# 3. Train Dataset
# ------------------------------------------------------------

train_dataset = Week4ExposureDataset(
    hr_dir=HR_DIR,
    file_list=train_files,
    exposures=TRAIN_EXPOSURES,
    patch_size=PATCH_SIZE,
    training=True,
    noise_on=True
)


# ------------------------------------------------------------
# 4. Validation Dataset
# ------------------------------------------------------------
# Val에서는 일단 Seen exposure만 사용.
# → 학습 중 best checkpoint 선택용
#
# Interpolation / Extrapolation은 나중에 최종 Test에서 평가.

val_dataset = Week4ExposureDataset(
    hr_dir=HR_DIR,
    file_list=val_files,
    exposures=TRAIN_EXPOSURES,
    patch_size=PATCH_SIZE,
    training=False,
    noise_on=True
)


# ------------------------------------------------------------
# 5. DataLoader
# ------------------------------------------------------------

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=0
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=0
)


# ------------------------------------------------------------
# 6. Dataset 확인
# ------------------------------------------------------------

print("=" * 70)
print("Week 4 Dataset / DataLoader")
print("=" * 70)

print("\n[Configuration]")
print("Patch size :", PATCH_SIZE)
print("Batch size :", BATCH_SIZE)

print("\n[Train]")
print("Images     :", len(train_files))
print("Exposures  :", TRAIN_EXPOSURES)
print("Samples    :", len(train_dataset))

print("\n[Validation]")
print("Images     :", len(val_files))
print("Exposures  :", TRAIN_EXPOSURES)
print("Samples    :", len(val_dataset))


# ------------------------------------------------------------
# 7. 실제 batch 하나 확인
# ------------------------------------------------------------

batch = next(iter(train_loader))

print("\n[Batch check]")

print(
    "Input shape       :",
    batch["input"].shape
)

print(
    "Target shape      :",
    batch["target"].shape
)

print(
    "Exposure norm     :",
    batch["exposure"]
)

print(
    "Exposure raw      :",
    batch["exposure_raw"]
)

print(
    "Pixel range input :",
    float(batch["input"].min()),
    "~",
    float(batch["input"].max())
)

print(
    "Pixel range target:",
    float(batch["target"].min()),
    "~",
    float(batch["target"].max())
)

print("=" * 70)

# ============================================================
# Week 4 - Cell 6
# SRCNN-no-exp / SRCNN-concat / FiLM-SRCNN
# ============================================================

import torch
import torch.nn as nn
import torch.nn.functional as F


# ------------------------------------------------------------
# 1. Baseline: SRCNN-no-exp
# ------------------------------------------------------------
# exposure 정보를 전혀 사용하지 않음
#
# Input:
#   degraded RGB image [B, 3, H, W]
#
# Network:
#   3 -> 64 -> 32 -> 3
# ------------------------------------------------------------

class SRCNNNoExposure(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(
            3, 64,
            kernel_size=9,
            padding=4
        )

        self.conv2 = nn.Conv2d(
            64, 32,
            kernel_size=5,
            padding=2
        )

        self.conv3 = nn.Conv2d(
            32, 3,
            kernel_size=5,
            padding=2
        )


    def forward(self, x, exposure=None):

        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = self.conv3(x)

        return x


# ------------------------------------------------------------
# 2. SRCNN-concat
# ------------------------------------------------------------
# exposure 값을 하나의 추가 channel로 만들어
# RGB image 뒤에 붙임.
#
# RGB          : 3 channels
# Exposure map : 1 channel
# -------------------------
# Input        : 4 channels
#
# 예:
# exposure normalized = 0.5
#
# exposure map 전체가
#
# [0.5 0.5 0.5 ...]
# [0.5 0.5 0.5 ...]
# [0.5 0.5 0.5 ...]
#
# 로 구성됨.
# ------------------------------------------------------------

class SRCNNConcat(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(
            4, 64,
            kernel_size=9,
            padding=4
        )

        self.conv2 = nn.Conv2d(
            64, 32,
            kernel_size=5,
            padding=2
        )

        self.conv3 = nn.Conv2d(
            32, 3,
            kernel_size=5,
            padding=2
        )


    def forward(self, x, exposure):

        B, _, H, W = x.shape

        # [B] -> [B,1,1,1]
        e = exposure.view(B, 1, 1, 1)

        # spatial exposure map
        e_map = e.expand(
            B, 1, H, W
        )

        # RGB + exposure
        x = torch.cat(
            [x, e_map],
            dim=1
        )

        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = self.conv3(x)

        return x


# ------------------------------------------------------------
# 3. FiLM layer
# ------------------------------------------------------------
#
# FiLM:
#
#       feature'
#          =
# gamma(exposure) * feature
#          +
# beta(exposure)
#
# exposure에 따라 각 feature channel을
# scale / shift 함.
# ------------------------------------------------------------

class FiLMLayer(nn.Module):

    def __init__(
        self,
        num_channels,
        hidden_dim=32
    ):
        super().__init__()

        self.mlp = nn.Sequential(

            nn.Linear(
                1,
                hidden_dim
            ),

            nn.ReLU(),

            nn.Linear(
                hidden_dim,
                2 * num_channels
            )
        )


    def forward(
        self,
        feature,
        exposure
    ):

        B = feature.shape[0]

        # [B] -> [B,1]
        e = exposure.view(B, 1)

        params = self.mlp(e)

        gamma, beta = torch.chunk(
            params,
            2,
            dim=1
        )

        # [B,C] -> [B,C,1,1]
        gamma = gamma.view(
            B, -1, 1, 1
        )

        beta = beta.view(
            B, -1, 1, 1
        )

        # identity-centered modulation
        feature = (
            (1.0 + gamma) * feature
            + beta
        )

        return feature


# ------------------------------------------------------------
# 4. FiLM-SRCNN
# ------------------------------------------------------------
#
# degraded image
#       |
#     Conv1
#       |
#     FiLM1  <- exposure
#       |
#     Conv2
#       |
#     FiLM2  <- exposure
#       |
#     Conv3
#       |
#   Restored image
# ------------------------------------------------------------

class FiLMSRCNN(nn.Module):

    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(
            3, 64,
            kernel_size=9,
            padding=4
        )

        self.film1 = FiLMLayer(
            num_channels=64
        )

        self.conv2 = nn.Conv2d(
            64, 32,
            kernel_size=5,
            padding=2
        )

        self.film2 = FiLMLayer(
            num_channels=32
        )

        self.conv3 = nn.Conv2d(
            32, 3,
            kernel_size=5,
            padding=2
        )


    def forward(
        self,
        x,
        exposure
    ):

        # Conv 1
        x = self.conv1(x)

        # Exposure-dependent modulation
        x = self.film1(
            x,
            exposure
        )

        x = F.relu(x)


        # Conv 2
        x = self.conv2(x)

        # Exposure-dependent modulation
        x = self.film2(
            x,
            exposure
        )

        x = F.relu(x)


        # reconstruction
        x = self.conv3(x)

        return x


# ------------------------------------------------------------
# 5. 모델 생성
# ------------------------------------------------------------

model_noexp = SRCNNNoExposure().to(device)

model_concat = SRCNNConcat().to(device)

model_film = FiLMSRCNN().to(device)


# ------------------------------------------------------------
# 6. Parameter 수 확인
# ------------------------------------------------------------

def count_parameters(model):

    return sum(
        p.numel()
        for p in model.parameters()
        if p.requires_grad
    )


print("=" * 70)
print("Week 4 Models")
print("=" * 70)

print(
    "SRCNN-no-exp :",
    f"{count_parameters(model_noexp):,}",
    "parameters"
)

print(
    "SRCNN-concat :",
    f"{count_parameters(model_concat):,}",
    "parameters"
)

print(
    "FiLM-SRCNN   :",
    f"{count_parameters(model_film):,}",
    "parameters"
)


# ------------------------------------------------------------
# 7. Forward test
# ------------------------------------------------------------

batch = next(iter(train_loader))

x = batch["input"].to(device)

e = batch["exposure"].to(device)


with torch.no_grad():

    y_noexp = model_noexp(
        x
    )

    y_concat = model_concat(
        x,
        e
    )

    y_film = model_film(
        x,
        e
    )


print("\n[Forward check]")

print("Input  :", x.shape)

print(
    "No-exp :",
    y_noexp.shape
)

print(
    "Concat :",
    y_concat.shape
)

print(
    "FiLM   :",
    y_film.shape
)

assert y_noexp.shape == x.shape
assert y_concat.shape == x.shape
assert y_film.shape == x.shape

print("\nForward shape check : PASS")
print("=" * 70)

# ============================================================
# Week 4 - Cell 7
# Common Training + Validation
# ============================================================

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. Training configuration
# ------------------------------------------------------------

NUM_ITER = 1000
LR = 1e-4

VAL_INTERVAL = 100

WEEK4_RESULT_DIR = os.path.join(
    RESULT_DIR,
    "week4"
)

os.makedirs(
    WEEK4_RESULT_DIR,
    exist_ok=True
)


# ------------------------------------------------------------
# 2. Seed 고정 함수
# ------------------------------------------------------------

def set_seed(seed=42):

    random.seed(seed)
    np.random.seed(seed)

    torch.manual_seed(seed)

    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


# ------------------------------------------------------------
# 3. PSNR
# ------------------------------------------------------------

def calc_psnr(pred, target):

    pred = torch.clamp(
        pred,
        0.0,
        1.0
    )

    target = torch.clamp(
        target,
        0.0,
        1.0
    )

    mse = torch.mean(
        (pred - target) ** 2,
        dim=(1, 2, 3)
    )

    psnr = 10.0 * torch.log10(
        1.0 / (mse + 1e-10)
    )

    return psnr


# ------------------------------------------------------------
# 4. Validation
# ------------------------------------------------------------

@torch.no_grad()
def validate_model(
    model,
    loader,
    device
):

    model.eval()

    psnr_values = []

    for batch in loader:

        x = batch["input"].to(device)
        y = batch["target"].to(device)
        e = batch["exposure"].to(device)

        pred = model(
            x,
            e
        )

        psnr = calc_psnr(
            pred,
            y
        )

        psnr_values.extend(
            psnr.cpu().tolist()
        )

    return float(
        np.mean(psnr_values)
    )


# ------------------------------------------------------------
# 5. 공통 training 함수
# ------------------------------------------------------------

def train_model(
    model,
    model_name,
    train_loader,
    val_loader,
    device,
    num_iter=5000,
    lr=1e-4,
    val_interval=100
):

    print("\n" + "=" * 75)
    print(f"Training : {model_name}")
    print("=" * 75)

    model = model.to(device)

    criterion = nn.L1Loss()

    optimizer = optim.Adam(
        model.parameters(),
        lr=lr
    )

    # --------------------------------------------
    # History
    # --------------------------------------------

    train_history = []

    val_steps = []
    val_history = []

    best_psnr = -float("inf")
    best_step = 0

    save_path = os.path.join(
        WEEK4_RESULT_DIR,
        f"{model_name}_best.pt"
    )

    # DataLoader를 계속 순환시키기 위한 iterator
    train_iter = iter(train_loader)


    # --------------------------------------------
    # Training
    # --------------------------------------------

    for step in range(
        1,
        num_iter + 1
    ):

        model.train()

        # ----------------------------------------
        # batch 가져오기
        # 끝까지 갔으면 새 epoch 시작
        # ----------------------------------------

        try:

            batch = next(train_iter)

        except StopIteration:

            train_iter = iter(train_loader)
            batch = next(train_iter)


        x = batch["input"].to(device)
        y = batch["target"].to(device)
        e = batch["exposure"].to(device)


        # ----------------------------------------
        # Forward
        # ----------------------------------------

        pred = model(
            x,
            e
        )


        # ----------------------------------------
        # Loss
        # ----------------------------------------

        loss = criterion(
            pred,
            y
        )


        # ----------------------------------------
        # Backpropagation
        # ----------------------------------------

        optimizer.zero_grad()

        loss.backward()

        optimizer.step()


        train_history.append(
            float(loss.item())
        )


        # ----------------------------------------
        # Validation
        # ----------------------------------------

        if (
            step == 1
            or step % val_interval == 0
            or step == num_iter
        ):

            val_psnr = validate_model(
                model,
                val_loader,
                device
            )

            val_steps.append(step)
            val_history.append(val_psnr)


            print(
                f"[{model_name}] "
                f"Step {step:4d}/{num_iter} | "
                f"L1={loss.item():.6f} | "
                f"Val PSNR={val_psnr:.4f} dB"
            )


            # ------------------------------------
            # Best checkpoint
            # ------------------------------------

            if val_psnr > best_psnr:

                best_psnr = val_psnr
                best_step = step

                torch.save(
                    {
                        "model_state_dict":
                            model.state_dict(),

                        "step":
                            step,

                        "val_psnr":
                            val_psnr,

                        "model_name":
                            model_name
                    },
                    save_path
                )


    # --------------------------------------------------------
    # 학습 완료
    # --------------------------------------------------------

    print("\nTraining finished.")

    print(
        f"Best validation PSNR : "
        f"{best_psnr:.4f} dB"
    )

    print(
        f"Best step            : "
        f"{best_step}"
    )

    print(
        f"Checkpoint           : "
        f"{save_path}"
    )

    print("=" * 75)


    return {
        "model": model,

        "train_loss":
            train_history,

        "val_steps":
            val_steps,

        "val_psnr":
            val_history,

        "best_psnr":
            best_psnr,

        "best_step":
            best_step,

        "checkpoint":
            save_path
    }

# ============================================================
# Week 4 - Cell 8
# Train all three models
# ============================================================


# ------------------------------------------------------------
# 1. SRCNN-no-exp
# ------------------------------------------------------------

set_seed(SEED)

model_noexp = SRCNNNoExposure().to(device)

result_noexp = train_model(
    model=model_noexp,
    model_name="srcnn_noexp",
    train_loader=train_loader,
    val_loader=val_loader,
    device=device,
    num_iter=NUM_ITER,
    lr=LR,
    val_interval=VAL_INTERVAL
)


# ------------------------------------------------------------
# 2. SRCNN-concat
# ------------------------------------------------------------

set_seed(SEED)

model_concat = SRCNNConcat().to(device)

result_concat = train_model(
    model=model_concat,
    model_name="srcnn_concat",
    train_loader=train_loader,
    val_loader=val_loader,
    device=device,
    num_iter=NUM_ITER,
    lr=LR,
    val_interval=VAL_INTERVAL
)


# ------------------------------------------------------------
# 3. FiLM-SRCNN
# ------------------------------------------------------------

set_seed(SEED)

model_film = FiLMSRCNN().to(device)

result_film = train_model(
    model=model_film,
    model_name="film_srcnn",
    train_loader=train_loader,
    val_loader=val_loader,
    device=device,
    num_iter=NUM_ITER,
    lr=LR,
    val_interval=VAL_INTERVAL
)


print("\n" + "=" * 75)
print("ALL TRAINING COMPLETE")
print("=" * 75)

print(
    f"No-exp | Best PSNR = "
    f"{result_noexp['best_psnr']:.4f} dB "
    f"@ step {result_noexp['best_step']}"
)

print(
    f"Concat | Best PSNR = "
    f"{result_concat['best_psnr']:.4f} dB "
    f"@ step {result_concat['best_step']}"
)

print(
    f"FiLM   | Best PSNR = "
    f"{result_film['best_psnr']:.4f} dB "
    f"@ step {result_film['best_step']}"
)

# ============================================================
# Week 4 - Cell 9
# Validation PSNR Curve
# ============================================================

import os
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. 결과 가져오기
# ------------------------------------------------------------

steps_noexp = result_noexp["val_steps"]
psnr_noexp = result_noexp["val_psnr"]

steps_concat = result_concat["val_steps"]
psnr_concat = result_concat["val_psnr"]

steps_film = result_film["val_steps"]
psnr_film = result_film["val_psnr"]


# ------------------------------------------------------------
# 2. Validation PSNR curve
# ------------------------------------------------------------

plt.figure(figsize=(9, 6))

plt.plot(
    steps_noexp,
    psnr_noexp,
    marker="o",
    linewidth=2,
    label="SRCNN No Exposure"
)

plt.plot(
    steps_concat,
    psnr_concat,
    marker="s",
    linewidth=2,
    label="SRCNN + Concat"
)

plt.plot(
    steps_film,
    psnr_film,
    marker="^",
    linewidth=2,
    label="FiLM-SRCNN"
)

plt.xlabel("Training Iteration")
plt.ylabel("Validation PSNR (dB)")

plt.title(
    "Validation PSNR vs Training Iteration"
)

plt.grid(
    True,
    alpha=0.3
)

plt.legend()

plt.tight_layout()


# ------------------------------------------------------------
# 3. 저장
# ------------------------------------------------------------

save_path = os.path.join(
    WEEK4_RESULT_DIR,
    "validation_psnr_curve.png"
)

plt.savefig(
    save_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 4. Best result 출력
# ------------------------------------------------------------

print("=" * 70)
print("Best Validation Results")
print("=" * 70)

print(
    f"No-exp : "
    f"{result_noexp['best_psnr']:.4f} dB "
    f"@ step {result_noexp['best_step']}"
)

print(
    f"Concat : "
    f"{result_concat['best_psnr']:.4f} dB "
    f"@ step {result_concat['best_step']}"
)

print(
    f"FiLM   : "
    f"{result_film['best_psnr']:.4f} dB "
    f"@ step {result_film['best_step']}"
)

print("\nSaved:", save_path)
print("=" * 70)

# ============================================================
# Week 4 - Cell 10
# Final Test: Seen / Interpolation / Extrapolation
# Metrics: PSNR + SSIM
# ============================================================

import os
import numpy as np
import torch
from torch.utils.data import DataLoader

# SSIM
from skimage.metrics import structural_similarity as skimage_ssim


# ------------------------------------------------------------
# 1. Best checkpoint 불러오기
# ------------------------------------------------------------

def load_best_model(model, checkpoint_path, device):

    checkpoint = torch.load(
        checkpoint_path,
        map_location=device
    )

    model.load_state_dict(
        checkpoint["model_state_dict"]
    )

    model = model.to(device)
    model.eval()

    print(
        f"Loaded: {checkpoint['model_name']} | "
        f"step={checkpoint['step']} | "
        f"Val PSNR={checkpoint['val_psnr']:.4f} dB"
    )

    return model


model_noexp_best = load_best_model(
    SRCNNNoExposure(),
    result_noexp["checkpoint"],
    device
)

model_concat_best = load_best_model(
    SRCNNConcat(),
    result_concat["checkpoint"],
    device
)

model_film_best = load_best_model(
    FiLMSRCNN(),
    result_film["checkpoint"],
    device
)


# ------------------------------------------------------------
# 2. Test Dataset 생성 함수
# ------------------------------------------------------------

def make_test_loader(exposures, noise_on=True):

    dataset = Week4ExposureDataset(
        hr_dir=HR_DIR,
        file_list=test_files,
        exposures=exposures,
        patch_size=PATCH_SIZE,
        training=False,
        noise_on=noise_on
    )

    loader = DataLoader(
        dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=0
    )

    return loader


# ------------------------------------------------------------
# 3. Test loaders
# ------------------------------------------------------------

test_seen_loader = make_test_loader(
    TRAIN_EXPOSURES,
    noise_on=True
)

test_interp_loader = make_test_loader(
    INTERP_EXPOSURES,
    noise_on=True
)

test_extrap_loader = make_test_loader(
    EXTRAP_EXPOSURES,
    noise_on=True
)


print("\n[Test sample counts]")
print("Seen          :", len(test_seen_loader.dataset))
print("Interpolation :", len(test_interp_loader.dataset))
print("Extrapolation :", len(test_extrap_loader.dataset))


# ------------------------------------------------------------
# 4. SSIM 계산
# ------------------------------------------------------------

def calc_ssim_batch(pred, target):

    pred = torch.clamp(pred, 0.0, 1.0)
    target = torch.clamp(target, 0.0, 1.0)

    pred_np = pred.detach().cpu().numpy()
    target_np = target.detach().cpu().numpy()

    values = []

    for i in range(pred_np.shape[0]):

        # CHW -> HWC
        p = np.transpose(
            pred_np[i],
            (1, 2, 0)
        )

        t = np.transpose(
            target_np[i],
            (1, 2, 0)
        )

        value = skimage_ssim(
            t,
            p,
            data_range=1.0,
            channel_axis=2
        )

        values.append(value)

    return values


# ------------------------------------------------------------
# 5. 모델 평가
# ------------------------------------------------------------

@torch.no_grad()
def evaluate_model(model, loader, device):

    model.eval()

    all_psnr = []
    all_ssim = []

    for batch in loader:

        x = batch["input"].to(device)
        y = batch["target"].to(device)
        e = batch["exposure"].to(device)

        pred = model(
            x,
            e
        )

        # PSNR
        psnr = calc_psnr(
            pred,
            y
        )

        all_psnr.extend(
            psnr.cpu().tolist()
        )

        # SSIM
        ssim = calc_ssim_batch(
            pred,
            y
        )

        all_ssim.extend(ssim)

    return {
        "psnr": float(np.mean(all_psnr)),
        "ssim": float(np.mean(all_ssim))
    }


# ------------------------------------------------------------
# 6. 세 모델 × 세 exposure regime 평가
# ------------------------------------------------------------

models = {
    "No-exp": model_noexp_best,
    "Concat": model_concat_best,
    "FiLM": model_film_best
}

loaders = {
    "Seen": test_seen_loader,
    "Interpolation": test_interp_loader,
    "Extrapolation": test_extrap_loader
}


final_results = {}


for model_name, model in models.items():

    final_results[model_name] = {}

    print("\n" + "=" * 70)
    print(model_name)
    print("=" * 70)

    for regime, loader in loaders.items():

        result = evaluate_model(
            model,
            loader,
            device
        )

        final_results[model_name][regime] = result

        print(
            f"{regime:14s} | "
            f"PSNR = {result['psnr']:.4f} dB | "
            f"SSIM = {result['ssim']:.4f}"
        )


# ------------------------------------------------------------
# 7. 최종 표 출력
# ------------------------------------------------------------

print("\n")
print("=" * 105)
print("FINAL WEEK 4 TEST RESULTS")
print("=" * 105)

header = (
    f"{'Model':<10}"
    f"{'Seen PSNR':>14}"
    f"{'Seen SSIM':>14}"
    f"{'Interp PSNR':>16}"
    f"{'Interp SSIM':>15}"
    f"{'Extra PSNR':>15}"
    f"{'Extra SSIM':>14}"
)

print(header)
print("-" * 105)


for model_name in models.keys():

    s = final_results[model_name]["Seen"]
    i = final_results[model_name]["Interpolation"]
    e = final_results[model_name]["Extrapolation"]

    print(
        f"{model_name:<10}"
        f"{s['psnr']:>14.4f}"
        f"{s['ssim']:>14.4f}"
        f"{i['psnr']:>16.4f}"
        f"{i['ssim']:>15.4f}"
        f"{e['psnr']:>15.4f}"
        f"{e['ssim']:>14.4f}"
    )

print("=" * 105)

# ============================================================
# Week 4 - Cell 11
# Exposure-wise PSNR / SSIM Analysis
# ============================================================

import os
import matplotlib.pyplot as plt
import numpy as np


# ------------------------------------------------------------
# 1. 평가할 exposure
# ------------------------------------------------------------

ALL_TEST_EXPOSURES = [
    3, 5, 7, 9, 11,
    13, 15, 17, 19,
    21, 25
]


# ------------------------------------------------------------
# 2. Exposure 하나씩 평가
# ------------------------------------------------------------

exposure_results = {
    model_name: {
        "psnr": [],
        "ssim": []
    }
    for model_name in models.keys()
}


for exposure in ALL_TEST_EXPOSURES:

    # exposure 하나만 포함하는 test loader
    loader = make_test_loader(
        exposures=[exposure],
        noise_on=True
    )

    print("\n" + "-" * 70)
    print(f"Exposure = {exposure}")
    print("-" * 70)

    for model_name, model in models.items():

        result = evaluate_model(
            model,
            loader,
            device
        )

        exposure_results[model_name]["psnr"].append(
            result["psnr"]
        )

        exposure_results[model_name]["ssim"].append(
            result["ssim"]
        )

        print(
            f"{model_name:<8s} | "
            f"PSNR = {result['psnr']:.4f} dB | "
            f"SSIM = {result['ssim']:.4f}"
        )


# ------------------------------------------------------------
# 3. PSNR Curve
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

markers = {
    "No-exp": "o",
    "Concat": "s",
    "FiLM": "^"
}

for model_name in models.keys():

    plt.plot(
        ALL_TEST_EXPOSURES,
        exposure_results[model_name]["psnr"],
        marker=markers[model_name],
        linewidth=2,
        markersize=7,
        label=model_name
    )


# 학습 exposure 표시
for e in TRAIN_EXPOSURES:

    plt.axvline(
        x=e,
        color="gray",
        linestyle=":",
        alpha=0.18
    )


# interpolation / extrapolation 경계
plt.axvspan(
    19,
    25.5,
    color="orange",
    alpha=0.07,
    label="Extrapolation region"
)


plt.xlabel("Exposure / Motion Kernel Length")
plt.ylabel("PSNR (dB)")

plt.title(
    "Restoration Performance vs Exposure"
)

plt.xticks(ALL_TEST_EXPOSURES)

plt.grid(
    True,
    alpha=0.25
)

plt.legend()

plt.tight_layout()


psnr_save_path = os.path.join(
    WEEK4_RESULT_DIR,
    "exposure_vs_psnr.png"
)

plt.savefig(
    psnr_save_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 4. SSIM Curve
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))


for model_name in models.keys():

    plt.plot(
        ALL_TEST_EXPOSURES,
        exposure_results[model_name]["ssim"],
        marker=markers[model_name],
        linewidth=2,
        markersize=7,
        label=model_name
    )


for e in TRAIN_EXPOSURES:

    plt.axvline(
        x=e,
        color="gray",
        linestyle=":",
        alpha=0.18
    )


plt.axvspan(
    19,
    25.5,
    color="orange",
    alpha=0.07,
    label="Extrapolation region"
)


plt.xlabel("Exposure / Motion Kernel Length")
plt.ylabel("SSIM")

plt.title(
    "Structural Similarity vs Exposure"
)

plt.xticks(ALL_TEST_EXPOSURES)

plt.grid(
    True,
    alpha=0.25
)

plt.legend()

plt.tight_layout()


ssim_save_path = os.path.join(
    WEEK4_RESULT_DIR,
    "exposure_vs_ssim.png"
)

plt.savefig(
    ssim_save_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 5. Exposure별 결과 표
# ------------------------------------------------------------

print("\n")
print("=" * 100)
print("EXPOSURE-WISE RESULTS")
print("=" * 100)

print(
    f"{'Exp':>4} | "
    f"{'NoExp PSNR':>10} {'Concat PSNR':>12} {'FiLM PSNR':>10} | "
    f"{'NoExp SSIM':>10} {'Concat SSIM':>11} {'FiLM SSIM':>9}"
)

print("-" * 100)


for idx, exposure in enumerate(ALL_TEST_EXPOSURES):

    print(
        f"{exposure:>4} | "
        f"{exposure_results['No-exp']['psnr'][idx]:>10.4f} "
        f"{exposure_results['Concat']['psnr'][idx]:>12.4f} "
        f"{exposure_results['FiLM']['psnr'][idx]:>10.4f} | "
        f"{exposure_results['No-exp']['ssim'][idx]:>10.4f} "
        f"{exposure_results['Concat']['ssim'][idx]:>11.4f} "
        f"{exposure_results['FiLM']['ssim'][idx]:>9.4f}"
    )

print("=" * 100)

print("\nSaved:")
print(psnr_save_path)
print(ssim_save_path)

# ============================================================
# Week 4 - Cell 12
# Noise OFF vs Noise ON
# Metrics: PSNR + SSIM
#모델의 성능 저하가 주로 motion blur 때문인지, 추가 noise까지 들어왔을 때 conditioning
#방식별 robustness가 어떻게 달라지는지
# ============================================================

import numpy as np
import matplotlib.pyplot as plt
import os


# ------------------------------------------------------------
# 1. 평가 조건
# ------------------------------------------------------------

NOISE_TEST_EXPOSURES = [
    3, 5, 7, 9, 11,
    13, 15, 17, 19,
    21, 25
]

noise_conditions = {
    "Noise OFF": False,
    "Noise ON": True
}


# ------------------------------------------------------------
# 2. 결과 저장 dictionary
# ------------------------------------------------------------

noise_results = {
    model_name: {
        condition: {
            "psnr": [],
            "ssim": []
        }
        for condition in noise_conditions.keys()
    }
    for model_name in models.keys()
}


# ------------------------------------------------------------
# 3. Exposure × Noise condition 평가
# ------------------------------------------------------------

for condition_name, noise_on in noise_conditions.items():

    print("\n" + "=" * 75)
    print(condition_name)
    print("=" * 75)

    for exposure in NOISE_TEST_EXPOSURES:

        loader = make_test_loader(
            exposures=[exposure],
            noise_on=noise_on
        )

        print(f"\nExposure = {exposure}")

        for model_name, model in models.items():

            result = evaluate_model(
                model,
                loader,
                device
            )

            noise_results[
                model_name
            ][
                condition_name
            ]["psnr"].append(
                result["psnr"]
            )

            noise_results[
                model_name
            ][
                condition_name
            ]["ssim"].append(
                result["ssim"]
            )

            print(
                f"{model_name:<8s} | "
                f"PSNR={result['psnr']:.4f} dB | "
                f"SSIM={result['ssim']:.4f}"
            )


# ------------------------------------------------------------
# 4. 전체 exposure 평균 결과
# ------------------------------------------------------------

print("\n")
print("=" * 85)
print("AVERAGE PERFORMANCE : NOISE OFF vs NOISE ON")
print("=" * 85)

print(
    f"{'Model':<10} | "
    f"{'OFF PSNR':>10} "
    f"{'OFF SSIM':>10} | "
    f"{'ON PSNR':>10} "
    f"{'ON SSIM':>10} | "
    f"{'PSNR Drop':>10}"
)

print("-" * 85)


average_noise_results = {}


for model_name in models.keys():

    off_psnr = np.mean(
        noise_results[
            model_name
        ]["Noise OFF"]["psnr"]
    )

    off_ssim = np.mean(
        noise_results[
            model_name
        ]["Noise OFF"]["ssim"]
    )

    on_psnr = np.mean(
        noise_results[
            model_name
        ]["Noise ON"]["psnr"]
    )

    on_ssim = np.mean(
        noise_results[
            model_name
        ]["Noise ON"]["ssim"]
    )

    psnr_drop = off_psnr - on_psnr

    average_noise_results[model_name] = {
        "off_psnr": off_psnr,
        "off_ssim": off_ssim,
        "on_psnr": on_psnr,
        "on_ssim": on_ssim,
        "psnr_drop": psnr_drop
    }

    print(
        f"{model_name:<10} | "
        f"{off_psnr:>10.4f} "
        f"{off_ssim:>10.4f} | "
        f"{on_psnr:>10.4f} "
        f"{on_ssim:>10.4f} | "
        f"{psnr_drop:>10.4f}"
    )

print("=" * 85)


# ------------------------------------------------------------
# 5. PSNR: Noise OFF vs ON 그래프
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    3,
    figsize=(17, 5),
    sharey=True
)


colors = {
    "Noise OFF": "tab:blue",
    "Noise ON": "tab:red"
}


for ax, model_name in zip(
    axes,
    models.keys()
):

    for condition in noise_conditions.keys():

        ax.plot(
            NOISE_TEST_EXPOSURES,
            noise_results[
                model_name
            ][condition]["psnr"],
            marker="o",
            linewidth=2,
            color=colors[condition],
            label=condition
        )

    ax.set_title(model_name)

    ax.set_xlabel(
        "Exposure / Motion Kernel Length"
    )

    ax.set_xticks(
        NOISE_TEST_EXPOSURES
    )

    ax.grid(
        True,
        alpha=0.25
    )

    ax.legend()


axes[0].set_ylabel(
    "PSNR (dB)"
)

fig.suptitle(
    "Effect of Additional Noise on Restoration",
    fontsize=14
)

plt.tight_layout()


noise_psnr_path = os.path.join(
    WEEK4_RESULT_DIR,
    "noise_off_vs_on_psnr.png"
)

plt.savefig(
    noise_psnr_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


# ------------------------------------------------------------
# 6. SSIM: Noise OFF vs ON 그래프
# ------------------------------------------------------------

fig, axes = plt.subplots(
    1,
    3,
    figsize=(17, 5),
    sharey=True
)


for ax, model_name in zip(
    axes,
    models.keys()
):

    for condition in noise_conditions.keys():

        ax.plot(
            NOISE_TEST_EXPOSURES,
            noise_results[
                model_name
            ][condition]["ssim"],
            marker="o",
            linewidth=2,
            color=colors[condition],
            label=condition
        )

    ax.set_title(model_name)

    ax.set_xlabel(
        "Exposure / Motion Kernel Length"
    )

    ax.set_xticks(
        NOISE_TEST_EXPOSURES
    )

    ax.grid(
        True,
        alpha=0.25
    )

    ax.legend()


axes[0].set_ylabel(
    "SSIM"
)

fig.suptitle(
    "Effect of Additional Noise on Structural Similarity",
    fontsize=14
)

plt.tight_layout()


noise_ssim_path = os.path.join(
    WEEK4_RESULT_DIR,
    "noise_off_vs_on_ssim.png"
)

plt.savefig(
    noise_ssim_path,
    dpi=200,
    bbox_inches="tight"
)

plt.show()


print("\nSaved:")
print(noise_psnr_path)
print(noise_ssim_path)

# ============================================================
# Week 4 - Cell 13
# Qualitative Comparison
#
# Degraded → No-exp → Concat → FiLM → Ground Truth
# ============================================================

import os
import numpy as np
import torch
import matplotlib.pyplot as plt


# ------------------------------------------------------------
# 1. 비교할 exposure
# ------------------------------------------------------------

QUAL_EXPOSURES = {
    "Seen": 11,
    "Interpolation": 13,
    "Extrapolation": 25
}


# ------------------------------------------------------------
# 2. Tensor → display image
# ------------------------------------------------------------

def tensor_to_image(x):

    x = torch.clamp(
        x.detach().cpu(),
        0.0,
        1.0
    )

    x = x.squeeze(0)

    x = x.permute(
        1, 2, 0
    ).numpy()

    return x


# ------------------------------------------------------------
# 3. Exposure 하나에 대한 결과 얻기
# ------------------------------------------------------------

@torch.no_grad()
def get_visual_result(
    exposure,
    sample_index=0,
    noise_on=True
):

    loader = make_test_loader(
        exposures=[exposure],
        noise_on=noise_on
    )

    dataset = loader.dataset

    sample = dataset[sample_index]

    # batch dimension 추가
    x = sample["input"].unsqueeze(0).to(device)
    y = sample["target"].unsqueeze(0).to(device)

    e = sample["exposure"]

    if not torch.is_tensor(e):
        e = torch.tensor(e)

    e = e.unsqueeze(0).to(device)


    # --------------------------------------------------------
    # Prediction
    # --------------------------------------------------------

    pred_noexp = model_noexp_best(
        x,
        e
    )

    pred_concat = model_concat_best(
        x,
        e
    )

    pred_film = model_film_best(
        x,
        e
    )


    # --------------------------------------------------------
    # PSNR
    # --------------------------------------------------------

    psnr_input = calc_psnr(
        x,
        y
    ).item()

    psnr_noexp = calc_psnr(
        pred_noexp,
        y
    ).item()

    psnr_concat = calc_psnr(
        pred_concat,
        y
    ).item()

    psnr_film = calc_psnr(
        pred_film,
        y
    ).item()


    # --------------------------------------------------------
    # SSIM
    # --------------------------------------------------------

    ssim_input = calc_ssim_batch(
        x,
        y
    )[0]

    ssim_noexp = calc_ssim_batch(
        pred_noexp,
        y
    )[0]

    ssim_concat = calc_ssim_batch(
        pred_concat,
        y
    )[0]

    ssim_film = calc_ssim_batch(
        pred_film,
        y
    )[0]


    return {

        "input": tensor_to_image(x),

        "noexp": tensor_to_image(pred_noexp),

        "concat": tensor_to_image(pred_concat),

        "film": tensor_to_image(pred_film),

        "gt": tensor_to_image(y),

        "metrics": {

            "input":
                (psnr_input, ssim_input),

            "noexp":
                (psnr_noexp, ssim_noexp),

            "concat":
                (psnr_concat, ssim_concat),

            "film":
                (psnr_film, ssim_film)
        }
    }


# ------------------------------------------------------------
# 4. Visualization
# ------------------------------------------------------------

fig, axes = plt.subplots(
    len(QUAL_EXPOSURES),
    5,
    figsize=(17, 10)
)


for row, (regime, exposure) in enumerate(
    QUAL_EXPOSURES.items()
):

    result = get_visual_result(
        exposure=exposure,
        sample_index=0,
        noise_on=True
    )

    images = [

        result["input"],

        result["noexp"],

        result["concat"],

        result["film"],

        result["gt"]
    ]


    # --------------------------------------------------------
    # title에 metric 표시
    # --------------------------------------------------------

    m = result["metrics"]

    titles = [

        (
            "Degraded\n"
            f"PSNR {m['input'][0]:.2f} | "
            f"SSIM {m['input'][1]:.3f}"
        ),

        (
            "No-exp\n"
            f"PSNR {m['noexp'][0]:.2f} | "
            f"SSIM {m['noexp'][1]:.3f}"
        ),

        (
            "Concat\n"
            f"PSNR {m['concat'][0]:.2f} | "
            f"SSIM {m['concat'][1]:.3f}"
        ),

        (
            "FiLM\n"
            f"PSNR {m['film'][0]:.2f} | "
            f"SSIM {m['film'][1]:.3f}"
        ),

        "Ground Truth"
    ]


    for col in range(5):

        axes[row, col].imshow(
            images[col]
        )

        axes[row, col].set_title(
            titles[col],
            fontsize=10
        )

        axes[row, col].axis("off")


    # 왼쪽에 regime / exposure 표시
    axes[row, 0].set_ylabel(
        f"{regime}\nExposure = {exposure}",
        fontsize=11
    )


fig.suptitle(
    "Qualitative Comparison Across Exposure Conditions",
    fontsize=15
)

plt.tight_layout()


# ------------------------------------------------------------
# 5. 저장
# ------------------------------------------------------------

qual_save_path = os.path.join(
    WEEK4_RESULT_DIR,
    "qualitative_comparison.png"
)

plt.savefig(
    qual_save_path,
    dpi=250,
    bbox_inches="tight"
)

plt.show()


print(
    "Saved:",
    qual_save_path
)

# ============================================================
# Week 4 - Cell 14
# Model Selection with Config Flag
#
# MODEL_TYPE:
#   "noexp"  -> SRCNN without exposure conditioning
#   "concat" -> SRCNN with exposure concatenation
#   "film"   -> FiLM-conditioned SRCNN
# ============================================================

# ------------------------------------------------------------
# 1. Model config
# ------------------------------------------------------------

MODEL_TYPE = "film"
# 선택:
# "noexp"
# "concat"
# "film"


# ------------------------------------------------------------
# 2. Model factory
# ------------------------------------------------------------

def build_model(model_type):

    model_type = model_type.lower()

    if model_type == "noexp":

        model = SRCNNNoExposure()

    elif model_type == "concat":

        model = SRCNNConcat()

    elif model_type == "film":

        model = FiLMSRCNN()

    else:

        raise ValueError(
            f"Unknown MODEL_TYPE: {model_type}\n"
            "Choose from: 'noexp', 'concat', 'film'"
        )

    return model


# ------------------------------------------------------------
# 3. 선택한 모델 생성
# ------------------------------------------------------------

selected_model = build_model(
    MODEL_TYPE
).to(device)


# ------------------------------------------------------------
# 4. 확인
# ------------------------------------------------------------

print("=" * 60)
print("Week 4 Model Configuration")
print("=" * 60)

print("MODEL_TYPE :", MODEL_TYPE)
print(
    "Model class:",
    selected_model.__class__.__name__
)

print(
    "Parameters :",
    sum(
        p.numel()
        for p in selected_model.parameters()
    )
)

print("=" * 60)